{% set name = "pymatgen" %}
{% set version = "2023.05.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/pymatgen/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b4a319682fa197d8067ee29ef02e31c80591829cd2963214b8ef519aff171f3b

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pmg = pymatgen.cli.pmg:main
    - feff_plot_cross_section = pymatgen.cli.feff_plot_cross_section:main
    - feff_plot_dos = pymatgen.cli.feff_plot_dos:main
    - gaussian_analyzer = pymatgen.cli.gaussian_analyzer:main
    - get_environment = pymatgen.cli.get_environment:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.23
    - setuptools >=18.0
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - requests
    - ruamel.yaml >=0.17.0
    - monty >=3.0.2
    - scipy >=1.5.0
    - tabulate
    - spglib >=1.9.9.44
    - networkx >=2.2
    - matplotlib-base >=1.5
    - palettable >=3.1.1
    - sympy
    - pandas
    - plotly >=4.5.0
    - uncertainties >=3.1.4
    - pybtex
    - tqdm
    - mp-api >=0.27.3

test:
  imports:
    - pymatgen
    - pymatgen.alchemy
    - pymatgen.analysis
    - pymatgen.analysis.chemenv
    - pymatgen.analysis.chemenv.coordination_environments
    - pymatgen.analysis.chemenv.coordination_environments.coordination_geometries_files
    - pymatgen.analysis.chemenv.coordination_environments.strategy_files
    - pymatgen.analysis.chemenv.utils
    - pymatgen.analysis.cost
    - pymatgen.analysis.diffraction
    - pymatgen.analysis.elasticity
    - pymatgen.analysis.hhi
    - pymatgen.analysis.pourbaix_diagram
    - pymatgen.apps
    - pymatgen.apps.battery
    - pymatgen.apps.borg
    - pymatgen.cli
    - pymatgen.command_line
    - pymatgen.core
    - pymatgen.electronic_structure
    - pymatgen.entries
    - pymatgen.io
    - pymatgen.io.abinit
    - pymatgen.io.feff
    - pymatgen.io.lammps
    - pymatgen.io.vasp
    - pymatgen.ext.matproj
    - pymatgen.optimization
    - pymatgen.analysis.phase_diagram
    - pymatgen.analysis.structure_prediction
    - pymatgen.symmetry
    - pymatgen.transformations
    - pymatgen.util
    - pymatgen.vis
  commands:
    - pip check
    - pmg --help
    - feff_plot_cross_section --help
    - feff_plot_dos --help
    - gaussian_analyzer --help
    - get_environment --help
  requires:
    - pip

about:
  home: http://www.pymatgen.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Materials Genomics is an analysis code for materials science.
  description: |
    Python Materials Genomics is a robust materials analysis code that defines
    core object representations for structures and molecules with support for many
    electronic structure codes. It is currently the core analysis code powering the
    Materials Project (https://www.materialsproject.org).
  doc_url: http://www.pymatgen.org
  dev_url: https://github.com/materialsproject/pymatgen

extra:
  recipe-maintainers:
    - jan-janssen
    - shyuep
    - mkhorton
