{% set name = "pymatgen" %}
{% set version = "2025.4.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f24c061f93949680f99f409b87e3bbf013565cee9160891148faab19c3df60bb

build:
  skip: true  # [py<310]
  skip: true  # [py>312]
  entry_points:
    - pmg = pymatgen.cli.pmg:main
    - feff_plot_cross_section = pymatgen.cli.feff_plot_cross_section:main
    - feff_plot_dos = pymatgen.cli.feff_plot_dos:main
    - get_environment = pymatgen.cli.get_environment:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.23
    - setuptools >=65.0.0
    - numpy
    - pip
  run:
    - numpy
    - python
    - matplotlib-base >=3.8
    - monty >=2025.1.9
    - networkx >=2.7
    - palettable >=3.3.3
    - pandas >=2
    - plotly >=5.0.0
    - pybtex >=0.24.0
    - requests >=2.32
    - ruamel.yaml >=0.17.0
    - scipy >=1.14.1
    - spglib >=2.5
    - sympy >=1.3
    - tabulate >=0.9
    - typing_extensions
    - tqdm >=4.60
    - uncertainties >=3.1.4
    - joblib >=1

test:
  imports:
    - pymatgen
    - pymatgen.alchemy
    - pymatgen.analysis
    - pymatgen.analysis.chemenv
    - pymatgen.analysis.chemenv.coordination_environments
    - pymatgen.analysis.chemenv.coordination_environments.coordination_geometries_files
    # - pymatgen.analysis.chemenv.coordination_environments.strategy_files
    - pymatgen.analysis.chemenv.utils
    - pymatgen.analysis.cost
    - pymatgen.analysis.diffraction
    - pymatgen.analysis.elasticity
    - pymatgen.analysis.hhi
    - pymatgen.analysis.pourbaix_diagram
    - pymatgen.apps
    - pymatgen.apps.battery
    - pymatgen.apps.borg
    - pymatgen.cli
    - pymatgen.command_line
    - pymatgen.core
    - pymatgen.electronic_structure
    - pymatgen.entries
    - pymatgen.io
    - pymatgen.io.abinit
    - pymatgen.io.feff
    - pymatgen.io.lammps
    - pymatgen.io.vasp
    - pymatgen.ext.matproj
    - pymatgen.optimization
    - pymatgen.analysis.phase_diagram
    - pymatgen.analysis.structure_prediction
    - pymatgen.symmetry
    - pymatgen.transformations
    - pymatgen.util
    - pymatgen.vis
  commands:
    - pip check
    - pmg --help
    - feff_plot_cross_section --help
    - feff_plot_dos --help
    - get_environment --help
  requires:
    - pip

about:
  home: https://pymatgen.org
  summary: Python Materials Genomics is a robust materials analysis code that defines core object representations for structures and molecules with support for many electronic structure codes. It is currently the core analysis code powering the Materials Project (https://materialsproject.org).
  doc_url: https://pythonhosted.org/pymatgen/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - shyuep
    - mkhorton
