{% set name = "pymatgen" %}
{% set version = "2023.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymatgen-{{ version }}.tar.gz
  sha256: d4ea04e28607f26eb21a36a8486c929265a86dd9fab97bc43f2c49c81c0e2199

build:
  skip: true  # [py<39]
  entry_points:
    - pmg = pymatgen.cli.pmg:main
    - feff_plot_cross_section = pymatgen.cli.feff_plot_cross_section:main
    - feff_plot_dos = pymatgen.cli.feff_plot_dos:main
    - get_environment = pymatgen.cli.get_environment:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29.23
    - setuptools >=65.0.0
    - numpy
    - pip
  run:
    - python
    - matplotlib-base >=1.5
    - monty >=3.0.2
    - networkx >=2.2
    - palettable >=3.1.1
    - pandas
    - plotly >=4.5.0
    - pybtex
    - requests
    - ruamel.yaml >=0.17.0
    - scipy >=1.5.0
    - spglib >=2.0.2
    - sympy
    - tabulate
    - tqdm
    - uncertainties >=3.1.4
    - joblib
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymatgen
    - pymatgen.alchemy
    - pymatgen.analysis
    - pymatgen.analysis.chemenv
    - pymatgen.analysis.chemenv.coordination_environments
    - pymatgen.analysis.chemenv.coordination_environments.coordination_geometries_files
    - pymatgen.analysis.chemenv.coordination_environments.strategy_files
    - pymatgen.analysis.chemenv.utils
    - pymatgen.analysis.cost
    - pymatgen.analysis.diffraction
    - pymatgen.analysis.elasticity
    - pymatgen.analysis.hhi
    - pymatgen.apps
    - pymatgen.apps.battery
    - pymatgen.apps.borg
    - pymatgen.cli
    - pymatgen.command_line
    - pymatgen.core
    - pymatgen.electronic_structure
    - pymatgen.entries
    - pymatgen.io
    - pymatgen.io.abinit
    - pymatgen.io.feff
    - pymatgen.io.lammps
    - pymatgen.ext.matproj
    - pymatgen.optimization
    - pymatgen.analysis.phase_diagram
    - pymatgen.analysis.structure_prediction
    - pymatgen.symmetry
    - pymatgen.transformations
    - pymatgen.util
    - pymatgen.vis
  commands:
    - pip check
    - pmg --help
    - feff_plot_cross_section --help
    - feff_plot_dos --help
    - get_environment --help
  requires:
    - pip

about:
  home: https://pymatgen.org
  summary: Python Materials Genomics is a robust materials analysis code that defines core object representations for structures and molecules with support for many electronic structure codes. It is currently the core analysis code powering the Materials Project (https://materialsproject.org).
  doc_url: https://pythonhosted.org/pymatgen/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - shyuep
    - mkhorton
