schema_version: 1

context:
  name: pymatgen
  version: 2026.9.24

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/materialsproject/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: ea230adc431ba43cb184a1140fcbc4be7684fc0407754e0b45f04d9707e459b4

build:
  number: 0
  skip: match(python, "<=3.10")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pmg = pymatgen.cli.pmg:main
      - feff_plot_cross_section = pymatgen.cli.feff_plot_cross_section:main
      - feff_plot_dos = pymatgen.cli.feff_plot_dos:main
      - get_environment = pymatgen.cli.get_environment:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.23
    - setuptools >=65.0.0
    - numpy
    - pip
  run:
    - pymatgen-core >=2026.9.23
    - python
tests:
  - python:
      imports:
        - pymatgen
        - pymatgen.alchemy
        - pymatgen.analysis
        - pymatgen.analysis.chemenv
        - pymatgen.analysis.chemenv.coordination_environments
        - pymatgen.analysis.chemenv.coordination_environments.coordination_geometries_files
        - pymatgen.analysis.chemenv.utils
        - pymatgen.analysis.cost
        - pymatgen.analysis.diffraction
        - pymatgen.analysis.elasticity
        - pymatgen.analysis.hhi
        - pymatgen.analysis.pourbaix_diagram
        - pymatgen.apps
        - pymatgen.apps.battery
        - pymatgen.apps.borg
        - pymatgen.cli
        - pymatgen.command_line
        - pymatgen.core
        - pymatgen.electronic_structure
        - pymatgen.entries
        - pymatgen.io
        - pymatgen.io.abinit
        - pymatgen.io.feff
        - pymatgen.io.lammps
        - pymatgen.io.vasp
        - pymatgen.ext.matproj
        - pymatgen.optimization
        - pymatgen.analysis.phase_diagram
        - pymatgen.analysis.structure_prediction
        - pymatgen.symmetry
        - pymatgen.transformations
        - pymatgen.util
        - pymatgen.vis
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - pmg --help
      - feff_plot_cross_section --help
      - feff_plot_dos --help
      - get_environment --help

about:
  summary: Python Materials Genomics is a robust materials analysis code that defines core object representations for structures and molecules with support for many electronic structure codes. It is currently the core analysis code powering the Materials Project (https://materialsproject.org).
  license: MIT
  license_file: LICENSE
  homepage: https://pymatgen.org
  documentation: https://pythonhosted.org/pymatgen/

extra:
  recipe-maintainers:
    - jan-janssen
    - shyuep
    - mkhorton
